// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CrossingInfo.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_CROSSINGINFO_H_
#define _FAST_DDS_GENERATED_CROSSINGINFO_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "Gps.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CROSSINGINFO_SOURCE)
#define CROSSINGINFO_DllAPI __declspec( dllexport )
#else
#define CROSSINGINFO_DllAPI __declspec( dllimport )
#endif // CROSSINGINFO_SOURCE
#else
#define CROSSINGINFO_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CROSSINGINFO_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure CrossingInfoType defined by the user in the IDL file.
 * @ingroup CrossingInfo
 */
class CrossingInfoType
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CrossingInfoType();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CrossingInfoType();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CrossingInfoType that will be copied.
     */
    eProsima_user_DllExport CrossingInfoType(
            const CrossingInfoType& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CrossingInfoType that will be copied.
     */
    eProsima_user_DllExport CrossingInfoType(
            CrossingInfoType&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CrossingInfoType that will be copied.
     */
    eProsima_user_DllExport CrossingInfoType& operator =(
            const CrossingInfoType& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CrossingInfoType that will be copied.
     */
    eProsima_user_DllExport CrossingInfoType& operator =(
            CrossingInfoType&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CrossingInfoType object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CrossingInfoType& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CrossingInfoType object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CrossingInfoType& x) const;

    /*!
     * @brief This function sets a value in member danger
     * @param _danger New value for member danger
     */
    eProsima_user_DllExport void danger(
            bool _danger);

    /*!
     * @brief This function returns the value of member danger
     * @return Value of member danger
     */
    eProsima_user_DllExport bool danger() const;

    /*!
     * @brief This function returns a reference to member danger
     * @return Reference to member danger
     */
    eProsima_user_DllExport bool& danger();


    /*!
     * @brief This function sets a value in member crossing
     * @param _crossing New value for member crossing
     */
    eProsima_user_DllExport void crossing(
            bool _crossing);

    /*!
     * @brief This function returns the value of member crossing
     * @return Value of member crossing
     */
    eProsima_user_DllExport bool crossing() const;

    /*!
     * @brief This function returns a reference to member crossing
     * @return Reference to member crossing
     */
    eProsima_user_DllExport bool& crossing();


    /*!
     * @brief This function copies the value in member dummy
     * @param _dummy New value to be copied in member dummy
     */
    eProsima_user_DllExport void dummy(
            const std::string& _dummy);

    /*!
     * @brief This function moves the value in member dummy
     * @param _dummy New value to be moved in member dummy
     */
    eProsima_user_DllExport void dummy(
            std::string&& _dummy);

    /*!
     * @brief This function returns a constant reference to member dummy
     * @return Constant reference to member dummy
     */
    eProsima_user_DllExport const std::string& dummy() const;

    /*!
     * @brief This function returns a reference to member dummy
     * @return Reference to member dummy
     */
    eProsima_user_DllExport std::string& dummy();


    /*!
     * @brief This function copies the value in member coords
     * @param _coords New value to be copied in member coords
     */
    eProsima_user_DllExport void coords(
            const gps& _coords);

    /*!
     * @brief This function moves the value in member coords
     * @param _coords New value to be moved in member coords
     */
    eProsima_user_DllExport void coords(
            gps&& _coords);

    /*!
     * @brief This function returns a constant reference to member coords
     * @return Constant reference to member coords
     */
    eProsima_user_DllExport const gps& coords() const;

    /*!
     * @brief This function returns a reference to member coords
     * @return Reference to member coords
     */
    eProsima_user_DllExport gps& coords();

private:

    bool m_danger{false};
    bool m_crossing{false};
    std::string m_dummy;
    gps m_coords;

};

#endif // _FAST_DDS_GENERATED_CROSSINGINFO_H_



